# This file was generated by go2nix.
with import <nixpkgs> {};

with goPackages;

let
  vcss = [
    nix-prefetch-git
    # nix-prefetch-svn
    # nix-prefetch-bzr
    # nix-prefetch-hg
  ];
  
  generated = import ./generated.nix {
    inherit stdenv lib goPackages fetchgit fetchhg fetchbzr fetchsvn;
  };
in

pkgs.lib.overrideDerivation generated (old: {
  name = "go2nix";

  buildInputs = [ makeWrapper go-bindata.bin tools.bin ];

  src = ./.;

  allowGoReference = true;

  preBuild = ''go generate ./...'';
  postInstall = ''
    wrapProgram $bin/bin/go2nix \
      ${lib.flip lib.concatMapStrings vcss (vcs: ''
        --prefix PATH : ${vcs}/bin \
      '')} \
      --prefix PATH : ${git}/bin
  '';

})
