# This file was generated by go2nix.
with import <nixpkgs> {};
#{ stdenv, lib, go, goPackages, fetchgit, fetchhg, fetchbzr, fetchsvn }:

with goPackages;

buildGoPackage rec {
  name = "go2nix-${version}";
  version = "dev";

  buildInputs = [ go go-bindata.bin tools.bin ];
  goPackagePath = "github.com/kamilchm/go2nix";

  preBuild = ''
    go generate ./...
  '';

  src = ./.;

  extraSrcs = (builtins.attrValues rec {
    go-spew = {
      goPackagePath = "github.com/davecgh/go-spew";

      src = fetchgit {
        url = "https://github.com/davecgh/go-spew";
        rev = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d";
        sha256 = "8a57704bb43b0258452007505785e0b06c8f5c116d88000ae99c78f9277c4242";
      };
    };
    goconvey = {
      goPackagePath = "github.com/smartystreets/goconvey";

      src = fetchgit {
        url = "https://github.com/smartystreets/goconvey";
        rev = "bf05a3a16dad006e63e899124a2c6125028f6b31";
        sha256 = "99214a2f641ea39e5e44a3a183349de292b54d71972a1449c0e3df7657a84766";
      };
    };
    assertions = {
      goPackagePath = "github.com/smartystreets/assertions";

      src = fetchgit {
        url = "https://github.com/smartystreets/assertions";
        rev = "ac6b6f68ca3d6ac00a360d0fad0c844859ad131b";
        sha256 = "003ba08eebfc16a586073492dc4cac4894120d4996c842cb22172fa82c4ea287";
      };
    };
    go2nix = {
      goPackagePath = "github.com/kamilchm/go2nix";

      src = fetchgit {
        url = "https://github.com/kamilchm/go2nix";
        rev = "38719b9ec9069534e57b3ea8de31a6b81c8faf2b";
        sha256 = "ff7c7299169aca6cac2935253f2ed929bcd933a22f9fc4f54fcefa9335f5f61a";
      };
    };
    units = {
      goPackagePath = "github.com/alecthomas/units";

      src = fetchgit {
        url = "https://github.com/alecthomas/units";
        rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
        sha256 = "749598ffaa194a0913408766f8fe7f951fe058764b5d9668cd4ba785435ac5c8";
      };
    };
    go-difflib = {
      goPackagePath = "github.com/pmezard/go-difflib";

      src = fetchgit {
        url = "https://github.com/pmezard/go-difflib";
        rev = "d8ed2627bdf02c080bf22230dbb337003b7aba2d";
        sha256 = "7add4653bf46c029c67248ae1bc683c25dfce47a0ec12d07ecd9ae4f26b93270";
      };
    };
    vcs = {
      goPackagePath = "github.com/Masterminds/vcs";

      src = fetchgit {
        url = "https://github.com/Masterminds/vcs";
        rev = "9c0db6583837118d5df7c2ae38ab1c194e434b35";
        sha256 = "19e46e768a08d1e01f316a1b8a844ac461acdb09eec506e8c58c3c5365c253d3";
      };
    };
    tools = {
      goPackagePath = "golang.org/x/tools";

      src = fetchgit {
        url = "https://go.googlesource.com/tools";
        rev = "95cc01bac9af31b888c95e60ffc191bae43db13b";
        sha256 = "22dacea492b24d3812d1fe39d8cb6652de5d733fad94e000c095661faa64bbfd";
      };
    };
    net = {
      goPackagePath = "golang.org/x/net";

      src = fetchgit {
        url = "https://go.googlesource.com/net";
        rev = "b4e17d61b15679caf2335da776c614169a1b4643";
        sha256 = "ead00a6fb31f33550fd8bf46f310c6e70e9bdc22302f36e159cecff886287cb9";
      };
    };
    kingpin-v2 = {
      goPackagePath = "gopkg.in/alecthomas/kingpin.v2";

      src = fetchgit {
        url = "https://gopkg.in/alecthomas/kingpin.v2";
        rev = "21551c2a6259a8145110ca80a36e25c9d7624032";
        sha256 = "a950d265aa1b5e6debd04be50fa30027a729482e9337b202a389eb8e09c317fe";
      };
    };
    gls = {
      goPackagePath = "github.com/jtolds/gls";

      src = fetchgit {
        url = "https://github.com/jtolds/gls";
        rev = "9a4a02dbe491bef4bab3c24fd9f3087d6c4c6690";
        sha256 = "d5ca62889237c706b19e9b5a75a48964b443317325adabe8359f4e4a4f9f6fbf";
      };
    };
    template = {
      goPackagePath = "github.com/alecthomas/template";

      src = fetchgit {
        url = "https://github.com/alecthomas/template";
        rev = "14fd436dd20c3cc65242a9f396b61bfc8a3926fc";
        sha256 = "a26fb9ae5414e73dd5fbeb972bfb5d3f7a8d2aad1adf9e3e173fe4fdd8de3fa7";
      };
    };
    testify = {
      goPackagePath = "github.com/stretchr/testify";

      src = fetchgit {
        url = "https://github.com/stretchr/testify";
        rev = "67106a5111a06241c8d84952c33214675f51a34a";
        sha256 = "89a4687bc175fe7a6a34b08c3ca94a2a0524d3e30391947dd05b1522d8516029";
      };
    };
    
  });
}
