# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
#{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:
with import <nixpkgs> {};

buildGoPackage rec {
  name = "go2nix-unstable-${version}";
  version = "0.2-dev";

  goPackagePath = "github.com/kamilchm/go2nix";
  subPackages = [ "cmd/go2nix" ];

  src = ./.;

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
