# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "github.com/pelletier/go-buffruneio";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-buffruneio";
      rev = "c37440a7cf42ac63b919c752ca73a85067e05992";
      sha256 = "0l83p1gg6g5mmhmxjisrhfimhbm71lwn1r2w7d6siwwqm9q08sd2";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "5ccdfb18c776b740aecaf085c4d9a2779199c279";
      sha256 = "1jl44j58y62rhnwkzw3mvcj725gdyzs45pq4ga81qqxwqxs3czsq";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "e6cb469339aef5b7be0c89de730d5f3cc8e47e50";
      sha256 = "16q3ibisbzq8rx4irhzl2lw4nwr62x9ryv446kgic8ww3p30rlf9";
    };
  }
]
