# This file was generated by go2nix.
{ stdenv, lib, goPackages, fetchgit, fetchhg, fetchbzr, fetchsvn }:

with goPackages;

buildGoPackage rec {
  name = "go2nix-${version}";
  version = "20160308-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "1b03214f7bf3429410c1067d09df1febbf13cbff";

  
  goPackagePath = "github.com/kamilchm/go2nix";

  src = fetchgit {
    inherit rev;
    url = "git@github.com:kamilchm/go2nix.git";
    sha256 = "07dniwvqzhwkyp5804m4mv5nhkkfbmyg2cy9i8q2q28m8glcvrcd";
  };

  extraSrcs = [
    {
      goPackagePath = "github.com/Masterminds/vcs";

      src = fetchgit {
        url = "https://github.com/Masterminds/vcs";
        rev = "9c0db6583837118d5df7c2ae38ab1c194e434b35";
        sha256 = "1lskq9jm6g4cqpl0digf17dsqqf49a28l6va64gy1l88i9v6xr0r";
      };
    }
    {
      goPackagePath = "github.com/alecthomas/template";

      src = fetchgit {
        url = "https://github.com/alecthomas/template";
        rev = "14fd436dd20c3cc65242a9f396b61bfc8a3926fc";
        sha256 = "19rzvvcgvr1z2wz9xpqsmlm8syizbpxjp5zbzgakvrqlajpbjvx2";
      };
    }
    {
      goPackagePath = "github.com/alecthomas/units";

      src = fetchgit {
        url = "https://github.com/alecthomas/units";
        rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
        sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
      };
    }
    {
      goPackagePath = "gopkg.in/alecthomas/kingpin.v2";

      src = fetchgit {
        url = "https://gopkg.in/alecthomas/kingpin.v2";
        rev = "21551c2a6259a8145110ca80a36e25c9d7624032";
        sha256 = "1zhpqc4qxsw9lc1b4dwk5r42k9r702ihzrabs3mnsphvm9jx4l59";
      };
    }
     # can be improved with Go 1.6 http://talks.golang.org/2016/state-of-go.slide#14
  ];
}
