# This file was generated by go2nix.
{ stdenv, lib, goPackages, fetchgit, fetchhg, fetchbzr, fetchsvn }:

with goPackages;

buildGoPackage rec {
  name = "[[ .Pkg.Name ]]-${version}";
  version = "[[ .Pkg.UpdateDate.Format "20060102" ]]-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "[[ .Pkg.Revision ]]";

  [[ if ne .BuildTags "" ]]
  buildFlags = "--tags [[ .BuildTags ]]";
  [[ end ]]
  goPackagePath = "[[ .Pkg.ImportPath ]]";

  src = fetchgit {
    inherit rev;
    url = "[[ .Pkg.VcsRepo ]]";
    sha256 = "[[ .Pkg.Hash ]]";
  };

  extraSrcs = map ( jsonDep:
    {
      inherit (jsonDep) goPackagePath;
      src = if jsonDep.fetch.type == "git" then
        fetchgit {
          inherit (jsonDep.fetch) url rev sha256;
        }
        else {};
    }
  ) (builtins.fromJSON (builtins.readFile ./deps.json));
}
