# This file was generated by https://github.com/kamilchm/go2nix v[[ .Version ]]
[
[[- range .Deps ]]
  {
    goPackagePath = "[[ .GoPackagePath ]]";
    fetch = {
      type = "[[ .Fetch.Type ]]";
      url = "[[ .Fetch.Url ]]";
      rev = "[[ .Fetch.Rev ]]";
      sha256 = "[[ .Fetch.Sha256 ]]";
    };
  }
[[- end ]]
]
