# This file was generated by https://github.com/kamilchm/go2nix v[[ .Version ]]
[
[[- range .Deps ]]
  {
    goPackagePath = "[[ .Name ]]";
    fetch = {
      type = "[[ .Source.Type ]]";
      url = "[[ .Source.Url ]]";
      rev = "[[ .Revision ]]";
      sha256 = "[[ .Source.Sha256 ]]";
    };
  }
[[- end ]]
]
