# This file was generated by go2nix.
{ fetchgit, fetchhg, fetchbzr, fetchsvn }:

[
  {{ range . }}{
    goPackagePath = "{{ .ImportPath }}";

    src = fetch{{ .VcsCommand }} {
      url = "{{ .VcsRepo }}";
      rev = "{{ .Revision }}";
      sha256 = "{{ .Hash }}";
    };
  }
  {{ end }}
]
